version: '3.12'

volumes:
  data:

services:
  web:
    env_file:
    - ".env"
    build: .
    command: uvicorn main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 5000:8000
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5432:5432"